import Head from 'next/head'
import { Inter } from 'next/font/google'

import Layout from '@/components/layout/Layout'
import HeroSection from '@/components/HeroSection'
import CatalogSection from '@/components/CatalogSection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log("render")
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HeroSection/>
        <CatalogSection/>
      </Layout>
    </>
  )
}
