import Head from 'next/head'
import { Inter } from 'next/font/google'

import Layout from '@/components/layout/Layout'
import CatalogSection from '@/components/CatalogSection'

import { getCategoryList } from '@/services/category'
import { CategoryType } from '@/types/categoryTypes'
import { getProductList } from '@/services/products'
import { ProductType } from '@/types/productTypes'

const inter = Inter({ subsets: ['latin'] })

type HomeProps = {
  categories: CategoryType[];
  products: ProductType[];
}

export default function Home({
  categories,
  products
}: HomeProps) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        isShowHeroSection
        categories={categories}
      >
        <CatalogSection
          products={products}
        />
      </Layout>
    </>
  )
}

export async function getStaticProps() {
  try {
    const categories =  await getCategoryList();
    categories.sort((a, b) => b.name.length - a.name.length)

    const products = await getProductList();

    return {
      props: {
        categories,
        products
      }, 
    }
  } catch (error) {
    return {
      notFound: true
    }
  } 
}
